In [8]:
import pandas as pd
import numpy as np

In [9]:
conso = pd.read_csv(
    "../data/raw/consommation/household_data_60min_singleindex.csv"
)

conso.shape

(38454, 71)

In [10]:
meteo = pd.read_csv(
    "../data/raw/meteo/ndjamena_meteo.csv"
)

meteo.shape

(52608, 5)

In [11]:
solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=10
)

solaire.shape

(220631, 5)

In [12]:
print(conso.columns[:10])

print(meteo.columns)

print(solaire.columns)

Index(['utc_timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices'],
      dtype='str')
Index(['time', 'temperature_2m', 'relative_humidity_2m', 'surface_pressure',
       'wind_speed_10m'],
      dtype='str')
Index(['2001', '4', '1', '0', '0.0'], dtype='str')

In [13]:
meteo["time"] = pd.to_datetime(meteo["time"])

meteo.head()

,time,temperature_2m,relative_humidity_2m,surface_pressure,wind_speed_10m
0,2020-01-01 00:00:00,19.7,23,978.4,14.5
1,2020-01-01 01:00:00,18.7,26,978.2,13.8
2,2020-01-01 02:00:00,18.0,29,978.0,12.8
3,2020-01-01 03:00:00,17.5,30,978.4,12.0
4,2020-01-01 04:00:00,17.0,32,978.5,11.9

In [14]:
conso["utc_timestamp"] = pd.to_datetime(
    conso["utc_timestamp"]
)

conso.head()

,utc_timestamp,cet_cest_timestamp,DE_KN_industrial1_grid_import,DE_KN_industrial1_pv_1,DE_KN_industrial1_pv_2,DE_KN_industrial2_grid_import,DE_KN_industrial2_pv,DE_KN_industrial2_storage_charge,DE_KN_industrial2_storage_decharge,DE_KN_industrial3_area_offices,...,DE_KN_residential5_refrigerator,DE_KN_residential5_washing_machine,DE_KN_residential6_circulation_pump,DE_KN_residential6_dishwasher,DE_KN_residential6_freezer,DE_KN_residential6_grid_export,DE_KN_residential6_grid_import,DE_KN_residential6_pv,DE_KN_residential6_washing_machine,interpolated
0,2014-12-11 17:00:00+00:00,2014-12-11T18:00:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-12-11 18:00:00+00:00,2014-12-11T19:00:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-12-11 19:00:00+00:00,2014-12-11T20:00:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-12-11 20:00:00+00:00,2014-12-11T21:00:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-12-11 21:00:00+00:00,2014-12-11T22:00:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=9
)

print(solaire.columns)
solaire.head()

Index(['YEAR', 'MO', 'DY', 'HR', 'ALLSKY_SFC_SW_DWN'], dtype='str')

   YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN
0  2001   4   1   0                0.0
1  2001   4   1   1                0.0
2  2001   4   1   2                0.0
3  2001   4   1   3                0.0
4  2001   4   1   4                0.0

In [16]:
print(meteo.columns)

print(solaire.columns)

print(conso["utc_timestamp"].min())
print(conso["utc_timestamp"].max())

print(meteo["time"].min())
print(meteo["time"].max())

print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

Index(['time', 'temperature_2m', 'relative_humidity_2m', 'surface_pressure',
       'wind_speed_10m'],
      dtype='str')
Index(['YEAR', 'MO', 'DY', 'HR', 'ALLSKY_SFC_SW_DWN'], dtype='str')
2014-12-11 17:00:00+00:00
2019-05-01 22:00:00+00:00
2020-01-01 00:00:00
2025-12-31 23:00:00

KeyError: 'timestamp'

In [ ]:
print(solaire.columns.tolist())

['YEAR', 'MO', 'DY', 'HR', 'ALLSKY_SFC_SW_DWN']

In [ ]:
solaire.head()

   YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN
0  2001   4   1   0                0.0
1  2001   4   1   1                0.0
2  2001   4   1   2                0.0
3  2001   4   1   3                0.0
4  2001   4   1   4                0.0

In [ ]:
solaire["timestamp"] = pd.to_datetime(
    solaire[["YEAR", "MO", "DY", "HR"]]
    .rename(
        columns={
            "YEAR": "year",
            "MO": "month",
            "DY": "day",
            "HR": "hour"
        }
    )
)

solaire[["timestamp", "ALLSKY_SFC_SW_DWN"]].head()

            timestamp  ALLSKY_SFC_SW_DWN
0 2001-04-01 00:00:00                0.0
1 2001-04-01 01:00:00                0.0
2 2001-04-01 02:00:00                0.0
3 2001-04-01 03:00:00                0.0
4 2001-04-01 04:00:00                0.0

In [ ]:
print(conso["utc_timestamp"].min())
print(conso["utc_timestamp"].max())

print(meteo["time"].min())
print(meteo["time"].max())

print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

2014-12-11 17:00:00+00:00
2019-05-01 22:00:00+00:00
2020-01-01 00:00:00
2025-12-31 23:00:00
2001-04-01 00:00:00
2026-06-01 23:00:00

In [ ]:
meteo = pd.read_csv(
    "../data/raw/meteo/ndjamena_meteo.csv"
)

meteo["time"] = pd.to_datetime(meteo["time"])

print(meteo["time"].min())
print(meteo["time"].max())

2020-01-01 00:00:00
2025-12-31 23:00:00

In [ ]:
import pandas as pd

meteo = pd.read_csv("../data/raw/meteo/ndjamena_meteo.csv")

meteo["time"] = pd.to_datetime(meteo["time"])

print(meteo["time"].min())
print(meteo["time"].max())

2020-01-01 00:00:00
2025-12-31 23:00:00

In [ ]:
solaire["timestamp"] = pd.to_datetime(
    solaire[["YEAR","MO","DY","HR"]]
    .rename(columns={
        "YEAR":"year",
        "MO":"month",
        "DY":"day",
        "HR":"hour"
    })
)

print(solaire[["timestamp","ALLSKY_SFC_SW_DWN"]].head())

            timestamp  ALLSKY_SFC_SW_DWN
0 2001-04-01 00:00:00                0.0
1 2001-04-01 01:00:00                0.0
2 2001-04-01 02:00:00                0.0
3 2001-04-01 03:00:00                0.0
4 2001-04-01 04:00:00                0.0

In [ ]:
target = "DE_KN_residential1_grid_import"

df_conso = conso.copy()

df_conso["utc_timestamp"] = pd.to_datetime(
    df_conso["utc_timestamp"]
)

df_conso["conso_horaire"] = (
    df_conso[target].diff()
)

df_conso = df_conso.dropna()

In [ ]:
print(df_conso["utc_timestamp"].min())
print(df_conso["utc_timestamp"].max())

print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

NaT
NaT
2001-04-01 00:00:00
2026-06-01 23:00:00

In [ ]:
print(df_conso["utc_timestamp"].min())
print(df_conso["utc_timestamp"].max())

print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

NaT
NaT
2001-04-01 00:00:00
2026-06-01 23:00:00

In [ ]:
import pandas as pd

conso = pd.read_csv(
    "../data/raw/consommation/household_data_60min_singleindex.csv"
)

target = "DE_KN_residential1_grid_import"

df_conso = conso.copy()

df_conso["utc_timestamp"] = pd.to_datetime(
    df_conso["utc_timestamp"],
    utc=True
)

df_conso["conso_horaire"] = (
    df_conso[target].diff()
)

df_conso = df_conso.dropna(
    subset=["utc_timestamp", "conso_horaire"]
)

print(df_conso["utc_timestamp"].min())
print(df_conso["utc_timestamp"].max())

print(df_conso["conso_horaire"].describe())

2015-05-21 16:00:00+00:00
2017-03-12 23:00:00+00:00
count    15872.000000
mean         0.573102
std          0.367954
min          0.029000
25%          0.375000
50%          0.447000
75%          0.614000
max          4.083000
Name: conso_horaire, dtype: float64

In [ ]:
print(df_conso["utc_timestamp"].min())
print(df_conso["utc_timestamp"].max())

print(df_conso["conso_horaire"].describe())

2015-05-21 16:00:00+00:00
2017-03-12 23:00:00+00:00
count    15872.000000
mean         0.573102
std          0.367954
min          0.029000
25%          0.375000
50%          0.447000
75%          0.614000
max          4.083000
Name: conso_horaire, dtype: float64

In [ ]:
df_conso = df_conso.rename(
    columns={"utc_timestamp": "timestamp"}
)

In [ ]:
df = pd.merge(
    df_conso,
    solaire_filtre[["timestamp", "ALLSKY_SFC_SW_DWN"]],
    on="timestamp",
    how="inner"
)

print(df.shape)

df.head()

NameError: name 'solaire_filtre' is not defined

In [ ]:
solaire["timestamp"] = pd.to_datetime(
    solaire[["YEAR","MO","DY","HR"]]
    .rename(columns={
        "YEAR":"year",
        "MO":"month",
        "DY":"day",
        "HR":"hour"
    }),
    utc=True
)

print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

2001-04-01 00:00:00+00:00
2026-06-01 23:00:00+00:00

In [ ]:
solaire_filtre = solaire[
    (solaire["timestamp"] >= df_conso["utc_timestamp"].min()) &
    (solaire["timestamp"] <= df_conso["utc_timestamp"].max())
]

print(solaire_filtre.shape)

print(solaire_filtre["timestamp"].min())
print(solaire_filtre["timestamp"].max())

KeyError: 'utc_timestamp'

In [ ]:
print(df_conso.columns)

Index(['timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices',
       'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2',
       'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4',
       'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate',
       'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher',
       'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import',
       'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2',
       'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4',
       'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade',
       'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator',
       'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import',
       'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher',
       'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import',
       'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv',
       'DE_KN_residential1_washing_machine',
       'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher',
       'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import',
       'DE_KN_residential2_washing_machine',
       'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher',
       'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export',
       'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv',
       'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine',
       'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev',
       'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export',
       'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump',
       'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator',
       'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher',
       'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator',
       'DE_KN_residential5_washing_machine',
       'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher',
       'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export',
       'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'conso_horaire'],
      dtype='str')

In [ ]:
solaire_filtre = solaire[
    (solaire["timestamp"] >= df_conso["timestamp"].min()) &
    (solaire["timestamp"] <= df_conso["timestamp"].max())
]

In [ ]:
print(df_conso.columns)

print(df_conso["timestamp"].min())
print(df_conso["timestamp"].max())

Index(['timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices',
       'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2',
       'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4',
       'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate',
       'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher',
       'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import',
       'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2',
       'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4',
       'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade',
       'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator',
       'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import',
       'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher',
       'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import',
       'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv',
       'DE_KN_residential1_washing_machine',
       'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher',
       'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import',
       'DE_KN_residential2_washing_machine',
       'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher',
       'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export',
       'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv',
       'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine',
       'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev',
       'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export',
       'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump',
       'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator',
       'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher',
       'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator',
       'DE_KN_residential5_washing_machine',
       'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher',
       'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export',
       'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'conso_horaire'],
      dtype='str')
2015-05-21 16:00:00+00:00
2017-03-12 23:00:00+00:00

In [ ]:
df = pd.merge(
    df_conso,
    solaire_filtre[["timestamp", "ALLSKY_SFC_SW_DWN"]],
    on="timestamp",
    how="inner"
)

print(df.shape)
print(df.columns)

(15872, 73)
Index(['timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices',
       'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2',
       'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4',
       'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate',
       'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher',
       'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import',
       'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2',
       'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4',
       'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade',
       'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator',
       'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import',
       'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher',
       'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import',
       'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv',
       'DE_KN_residential1_washing_machine',
       'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher',
       'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import',
       'DE_KN_residential2_washing_machine',
       'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher',
       'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export',
       'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv',
       'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine',
       'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev',
       'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export',
       'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump',
       'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator',
       'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher',
       'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator',
       'DE_KN_residential5_washing_machine',
       'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher',
       'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export',
       'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'conso_horaire',
       'ALLSKY_SFC_SW_DWN'],
      dtype='str')

In [ ]:
print(df.columns.tolist())

['timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import', 'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2', 'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv', 'DE_KN_industrial2_storage_charge', 'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices', 'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2', 'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4', 'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate', 'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher', 'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import', 'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2', 'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4', 'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade', 'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator', 'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import', 'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher', 'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import', 'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv', 'DE_KN_residential1_washing_machine', 'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher', 'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import', 'DE_KN_residential2_washing_machine', 'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher', 'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export', 'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv', 'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine', 'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev', 'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export', 'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump', 'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator', 'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher', 'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator', 'DE_KN_residential5_washing_machine', 'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher', 'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export', 'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv', 'DE_KN_residential6_washing_machine', 'interpolated', 'conso_horaire', 'ALLSKY_SFC_SW_DWN']

In [ ]:

df[["conso_horaire","ALLSKY_SFC_SW_DWN"]].head()

   conso_horaire  ALLSKY_SFC_SW_DWN
0          0.375             285.35
1          0.563              87.95
2          0.527               0.00
3          0.580               0.00
4          0.510               0.00

In [ ]:
print(df.shape)

(15872, 73)

In [ ]:
df["hour"] = df["timestamp"].dt.hour

df["dayofweek"] = df["timestamp"].dt.dayofweek

df["month"] = df["timestamp"].dt.month

df["lag_1"] = df["conso_horaire"].shift(1)

df["lag_24"] = df["conso_horaire"].shift(24)

df["rolling_24"] = (
    df["conso_horaire"]
    .rolling(24)
    .mean()
)

df = df.dropna()

In [ ]:
print(df.columns)

Index(['timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices',
       'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2',
       'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4',
       'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate',
       'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher',
       'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import',
       'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2',
       'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4',
       'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade',
       'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator',
       'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import',
       'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher',
       'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import',
       'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv',
       'DE_KN_residential1_washing_machine',
       'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher',
       'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import',
       'DE_KN_residential2_washing_machine',
       'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher',
       'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export',
       'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv',
       'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine',
       'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev',
       'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export',
       'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump',
       'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator',
       'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher',
       'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator',
       'DE_KN_residential5_washing_machine',
       'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher',
       'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export',
       'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'conso_horaire',
       'ALLSKY_SFC_SW_DWN', 'hour', 'dayofweek', 'month', 'lag_1', 'lag_24',
       'rolling_24'],
      dtype='str')

In [ ]:
df[[
    "conso_horaire",
    "hour",
    "dayofweek",
    "month",
    "lag_1",
    "lag_24",
    "rolling_24",
    "ALLSKY_SFC_SW_DWN"
]].isna().sum()

conso_horaire        0
hour                 0
dayofweek            0
month                0
lag_1                0
lag_24               0
rolling_24           0
ALLSKY_SFC_SW_DWN    0
dtype: int64

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

features = [
    "hour",
    "dayofweek",
    "month",
    "lag_1",
    "lag_24",
    "rolling_24",
    "ALLSKY_SFC_SW_DWN"
]

X = df[features]
y = df["conso_horaire"]

split = int(len(df) * 0.8)

X_train = X.iloc[:split]
X_test = X.iloc[split:]

y_train = y.iloc[:split]
y_test = y.iloc[split:]

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

mae = mean_absolute_error(y_test, pred)
r2 = r2_score(y_test, pred)

print("MAE :", mae)
print("R² :", r2)

ValueError: Found array with 0 sample(s) (shape=(0, 7)) while a minimum of 1 is required by RandomForestRegressor.

In [ ]:
print(df.shape)

print(df["ALLSKY_SFC_SW_DWN"].isna().sum())

print(df["conso_horaire"].isna().sum())

(0, 79)
0
0

In [ ]:
print(df["timestamp"].min())
print(df["timestamp"].max())

NaT
NaT

In [ ]:
print(meteo["time"].min())
print(meteo["time"].max())

2020-01-01 00:00:00
2025-12-31 23:00:00

In [ ]:
print(conso["timestamp"].min())
print(conso["timestamp"].max())

KeyError: 'timestamp'

In [ ]:
conso = pd.read_csv(
    "../data/raw/consommation/household_data_60min_singleindex.csv"
)

meteo = pd.read_csv(
    "../data/raw/meteo/ndjamena_meteo.csv"
)

solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=10
)

In [ ]:
print(conso.shape)
print(meteo.shape)
print(solaire.shape)

(38454, 71)
(52608, 5)
(220631, 5)

In [ ]:
print(conso.head())
print(meteo.head())
print(solaire.head())

          utc_timestamp        cet_cest_timestamp  \
0  2014-12-11T17:00:00Z  2014-12-11T18:00:00+0100
1  2014-12-11T18:00:00Z  2014-12-11T19:00:00+0100
2  2014-12-11T19:00:00Z  2014-12-11T20:00:00+0100
3  2014-12-11T20:00:00Z  2014-12-11T21:00:00+0100
4  2014-12-11T21:00:00Z  2014-12-11T22:00:00+0100

   DE_KN_industrial1_grid_import  DE_KN_industrial1_pv_1  \
0                            NaN                     NaN
1                            NaN                     NaN
2                            NaN                     NaN
3                            NaN                     NaN
4                            NaN                     NaN

   DE_KN_industrial1_pv_2  DE_KN_industrial2_grid_import  \
0                     NaN                            NaN
1                     NaN                            NaN
2                     NaN                            NaN
3                     NaN                            NaN
4                     NaN                            NaN

   DE_KN_industrial2_pv  DE_KN_industrial2_storage_charge  \
0                   NaN                               NaN
1                   NaN                               NaN
2                   NaN                               NaN
3                   NaN                               NaN
4                   NaN                               NaN

   DE_KN_industrial2_storage_decharge  DE_KN_industrial3_area_offices  ...  \
0                                 NaN                             NaN  ...
1                                 NaN                             NaN  ...
2                                 NaN                             NaN  ...
3                                 NaN                             NaN  ...
4                                 NaN                             NaN  ...

   DE_KN_residential5_refrigerator  DE_KN_residential5_washing_machine  \
0                              NaN                                 NaN
1                              NaN                                 NaN
2                              NaN                                 NaN
3                              NaN                                 NaN
4                              NaN                                 NaN

   DE_KN_residential6_circulation_pump  DE_KN_residential6_dishwasher  \
0                                  NaN                            NaN
1                                  NaN                            NaN
2                                  NaN                            NaN
3                                  NaN                            NaN
4                                  NaN                            NaN

   DE_KN_residential6_freezer  DE_KN_residential6_grid_export  \
0                         NaN                             NaN
1                         NaN                             NaN
2                         NaN                             NaN
3                         NaN                             NaN
4                         NaN                             NaN

   DE_KN_residential6_grid_import  DE_KN_residential6_pv  \
0                             NaN                    NaN
1                             NaN                    NaN
2                             NaN                    NaN
3                             NaN                    NaN
4                             NaN                    NaN

   DE_KN_residential6_washing_machine  interpolated
0                                 NaN           NaN
1                                 NaN           NaN
2                                 NaN           NaN
3                                 NaN           NaN
4                                 NaN           NaN

[5 rows x 71 columns]
               time  temperature_2m  relative_humidity_2m  surface_pressure  \
0  2020-01-01T00:00            19.7                    23             978.4
1  2020-01-01T01:00            18.7                    26             978.2
2  2020-01-01T02:00            18.0                    29             978.0
3  2020-01-01T03:00            17.5                    30             978.4
4  2020-01-01T04:00            17.0                    32             978.5

   wind_speed_10m
0            14.5
1            13.8
2            12.8
3            12.0
4            11.9
   2001  4  1  0  0.0
0  2001  4  1  1  0.0
1  2001  4  1  2  0.0
2  2001  4  1  3  0.0
3  2001  4  1  4  0.0
4  2001  4  1  5  0.0

In [ ]:
import pandas as pd

conso = pd.read_csv(
    "../data/raw/consommation/household_data_60min_singleindex.csv"
)

meteo = pd.read_csv(
    "../data/raw/meteo/ndjamena_meteo.csv"
)

solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=10
)

In [ ]:
print("CONSO :", conso.shape)
print("METEO :", meteo.shape)
print("SOLAIRE :", solaire.shape)

CONSO : (38454, 71)
METEO : (52608, 5)
SOLAIRE : (220631, 5)

In [ ]:
print(conso.head(2))
print(meteo.head(2))
print(solaire.head(2))

          utc_timestamp        cet_cest_timestamp  \
0  2014-12-11T17:00:00Z  2014-12-11T18:00:00+0100
1  2014-12-11T18:00:00Z  2014-12-11T19:00:00+0100

   DE_KN_industrial1_grid_import  DE_KN_industrial1_pv_1  \
0                            NaN                     NaN
1                            NaN                     NaN

   DE_KN_industrial1_pv_2  DE_KN_industrial2_grid_import  \
0                     NaN                            NaN
1                     NaN                            NaN

   DE_KN_industrial2_pv  DE_KN_industrial2_storage_charge  \
0                   NaN                               NaN
1                   NaN                               NaN

   DE_KN_industrial2_storage_decharge  DE_KN_industrial3_area_offices  ...  \
0                                 NaN                             NaN  ...
1                                 NaN                             NaN  ...

   DE_KN_residential5_refrigerator  DE_KN_residential5_washing_machine  \
0                              NaN                                 NaN
1                              NaN                                 NaN

   DE_KN_residential6_circulation_pump  DE_KN_residential6_dishwasher  \
0                                  NaN                            NaN
1                                  NaN                            NaN

   DE_KN_residential6_freezer  DE_KN_residential6_grid_export  \
0                         NaN                             NaN
1                         NaN                             NaN

   DE_KN_residential6_grid_import  DE_KN_residential6_pv  \
0                             NaN                    NaN
1                             NaN                    NaN

   DE_KN_residential6_washing_machine  interpolated
0                                 NaN           NaN
1                                 NaN           NaN

[2 rows x 71 columns]
               time  temperature_2m  relative_humidity_2m  surface_pressure  \
0  2020-01-01T00:00            19.7                    23             978.4
1  2020-01-01T01:00            18.7                    26             978.2

   wind_speed_10m
0            14.5
1            13.8
   2001  4  1  0  0.0
0  2001  4  1  1  0.0
1  2001  4  1  2  0.0

In [ ]:
conso["timestamp"] = pd.to_datetime(conso["utc_timestamp"])

meteo["time"] = pd.to_datetime(meteo["time"])

solaire["timestamp"] = pd.to_datetime(
    solaire[["YEAR","MO","DY","HR"]]
    .rename(
        columns={
            "YEAR":"year",
            "MO":"month",
            "DY":"day",
            "HR":"hour"
        }
    )
)

KeyError: "None of [Index(['YEAR', 'MO', 'DY', 'HR'], dtype='str')] are in the [columns]"

In [ ]:
print(solaire.columns.tolist())

['2001', '4', '1', '0', '0.0']

In [ ]:
print(solaire.head())

   2001  4  1  0  0.0
0  2001  4  1  1  0.0
1  2001  4  1  2  0.0
2  2001  4  1  3  0.0
3  2001  4  1  4  0.0
4  2001  4  1  5  0.0

In [ ]:
solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=9
)

In [ ]:
solaire["timestamp"] = pd.to_datetime(
    solaire[["YEAR","MO","DY","HR"]]
    .rename(
        columns={
            "YEAR":"year",
            "MO":"month",
            "DY":"day",
            "HR":"hour"
        }
    )
)

In [ ]:
print("CONSO")
print(conso["timestamp"].min())
print(conso["timestamp"].max())

print("\nMETEO")
print(meteo["time"].min())
print(meteo["time"].max())

print("\nSOLAIRE")
print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

CONSO
2014-12-11 17:00:00+00:00
2019-05-01 22:00:00+00:00

METEO
2020-01-01 00:00:00
2025-12-31 23:00:00

SOLAIRE
2001-04-01 00:00:00
2026-06-01 23:00:00

In [ ]:
solaire_filtre = solaire[
    (solaire["timestamp"] >= conso["timestamp"].min().tz_localize(None))
    &
    (solaire["timestamp"] <= conso["timestamp"].max().tz_localize(None))
]

In [ ]:
conso_merge = conso.copy()

conso_merge["timestamp_naive"] = (
    conso_merge["timestamp"]
    .dt.tz_localize(None)
)

In [ ]:
df = pd.merge(
    conso_merge,
    solaire_filtre[[
        "timestamp",
        "ALLSKY_SFC_SW_DWN"
    ]],
    left_on="timestamp_naive",
    right_on="timestamp",
    how="inner"
)

In [ ]:
print(df.shape)

print(df[[
    "conso_horaire",
    "ALLSKY_SFC_SW_DWN"
]].head())

(38454, 75)

KeyError: "['conso_horaire'] not in index"

In [ ]:
print(df.columns.tolist())

['utc_timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import', 'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2', 'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv', 'DE_KN_industrial2_storage_charge', 'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices', 'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2', 'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4', 'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate', 'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher', 'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import', 'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2', 'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4', 'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade', 'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator', 'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import', 'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher', 'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import', 'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv', 'DE_KN_residential1_washing_machine', 'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher', 'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import', 'DE_KN_residential2_washing_machine', 'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher', 'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export', 'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv', 'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine', 'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev', 'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export', 'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump', 'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator', 'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher', 'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator', 'DE_KN_residential5_washing_machine', 'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher', 'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export', 'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv', 'DE_KN_residential6_washing_machine', 'interpolated', 'timestamp_x', 'timestamp_naive', 'timestamp_y', 'ALLSKY_SFC_SW_DWN']

In [ ]:
df_conso["conso_horaire"] = (
    df_conso["DE_KN_residential1_grid_import"]
    .diff()
)

df_conso = df_conso.dropna()

In [ ]:
print(df_conso[[
    "DE_KN_residential1_grid_import",
    "conso_horaire"
]].head())

Empty DataFrame
Columns: [DE_KN_residential1_grid_import, conso_horaire]
Index: []

In [ ]:
print(df_conso.shape)
print(df_conso.columns[-5:])

(0, 72)
Index(['DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'conso_horaire'],
      dtype='str')

In [ ]:
print(df_conso.shape)

print(df_conso.columns)

print(df_conso.head())

(0, 72)
Index(['timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices',
       'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2',
       'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4',
       'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate',
       'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher',
       'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import',
       'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2',
       'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4',
       'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade',
       'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator',
       'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import',
       'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher',
       'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import',
       'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv',
       'DE_KN_residential1_washing_machine',
       'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher',
       'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import',
       'DE_KN_residential2_washing_machine',
       'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher',
       'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export',
       'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv',
       'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine',
       'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev',
       'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export',
       'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump',
       'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator',
       'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher',
       'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator',
       'DE_KN_residential5_washing_machine',
       'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher',
       'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export',
       'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'conso_horaire'],
      dtype='str')
Empty DataFrame
Columns: [timestamp, cet_cest_timestamp, DE_KN_industrial1_grid_import, DE_KN_industrial1_pv_1, DE_KN_industrial1_pv_2, DE_KN_industrial2_grid_import, DE_KN_industrial2_pv, DE_KN_industrial2_storage_charge, DE_KN_industrial2_storage_decharge, DE_KN_industrial3_area_offices, DE_KN_industrial3_area_room_1, DE_KN_industrial3_area_room_2, DE_KN_industrial3_area_room_3, DE_KN_industrial3_area_room_4, DE_KN_industrial3_compressor, DE_KN_industrial3_cooling_aggregate, DE_KN_industrial3_cooling_pumps, DE_KN_industrial3_dishwasher, DE_KN_industrial3_ev, DE_KN_industrial3_grid_import, DE_KN_industrial3_machine_1, DE_KN_industrial3_machine_2, DE_KN_industrial3_machine_3, DE_KN_industrial3_machine_4, DE_KN_industrial3_machine_5, DE_KN_industrial3_pv_facade, DE_KN_industrial3_pv_roof, DE_KN_industrial3_refrigerator, DE_KN_industrial3_ventilation, DE_KN_public1_grid_import, DE_KN_public2_grid_import, DE_KN_residential1_dishwasher, DE_KN_residential1_freezer, DE_KN_residential1_grid_import, DE_KN_residential1_heat_pump, DE_KN_residential1_pv, DE_KN_residential1_washing_machine, DE_KN_residential2_circulation_pump, DE_KN_residential2_dishwasher, DE_KN_residential2_freezer, DE_KN_residential2_grid_import, DE_KN_residential2_washing_machine, DE_KN_residential3_circulation_pump, DE_KN_residential3_dishwasher, DE_KN_residential3_freezer, DE_KN_residential3_grid_export, DE_KN_residential3_grid_import, DE_KN_residential3_pv, DE_KN_residential3_refrigerator, DE_KN_residential3_washing_machine, DE_KN_residential4_dishwasher, DE_KN_residential4_ev, DE_KN_residential4_freezer, DE_KN_residential4_grid_export, DE_KN_residential4_grid_import, DE_KN_residential4_heat_pump, DE_KN_residential4_pv, DE_KN_residential4_refrigerator, DE_KN_residential4_washing_machine, DE_KN_residential5_dishwasher, DE_KN_residential5_grid_import, DE_KN_residential5_refrigerator, DE_KN_residential5_washing_machine, DE_KN_residential6_circulation_pump, DE_KN_residential6_dishwasher, DE_KN_residential6_freezer, DE_KN_residential6_grid_export, DE_KN_residential6_grid_import, DE_KN_residential6_pv, DE_KN_residential6_washing_machine, interpolated, conso_horaire]
Index: []

[0 rows x 72 columns]

In [ ]:
print(conso.shape)

print(conso["DE_KN_residential1_grid_import"].count())

print(conso["timestamp"].min())

print(conso["timestamp"].max())

(38454, 72)
15873
2014-12-11 17:00:00+00:00
2019-05-01 22:00:00+00:00

In [ ]:
df_conso = conso.copy()

df_conso = df_conso[
    ["timestamp", "DE_KN_residential1_grid_import"]
]

df_conso = df_conso.dropna()

df_conso["conso_horaire"] = (
    df_conso["DE_KN_residential1_grid_import"]
    .diff()
)

df_conso = df_conso.dropna()

print(df_conso.shape)

df_conso.head()

(15872, 3)

                     timestamp  DE_KN_residential1_grid_import  conso_horaire
3863 2015-05-21 16:00:00+00:00                           0.482          0.375
3864 2015-05-21 17:00:00+00:00                           1.045          0.563
3865 2015-05-21 18:00:00+00:00                           1.572          0.527
3866 2015-05-21 19:00:00+00:00                           2.152          0.580
3867 2015-05-21 20:00:00+00:00                           2.662          0.510

In [ ]:
print(df_conso["timestamp"].min())
print(df_conso["timestamp"].max())

print(df_conso["conso_horaire"].describe())

2015-05-21 16:00:00+00:00
2017-03-12 23:00:00+00:00
count    15872.000000
mean         0.573102
std          0.367954
min          0.029000
25%          0.375000
50%          0.447000
75%          0.614000
max          4.083000
Name: conso_horaire, dtype: float64

In [ ]:
df = pd.merge(
    df_conso,
    solaire[["timestamp", "ALLSKY_SFC_SW_DWN"]],
    on="timestamp",
    how="inner"
)

print(df.shape)

df.head()

ValueError: You are trying to merge on datetime64[us, UTC] and datetime64[us] columns for key 'timestamp'. If you wish to proceed you should use pd.concat

In [ ]:
df_conso["timestamp"] = (
    df_conso["timestamp"]
    .dt.tz_localize(None)
)

In [ ]:
print(df_conso["timestamp"].dtype)

print(solaire["timestamp"].dtype)

datetime64[us]
datetime64[us]

In [ ]:
df = pd.merge(
    df_conso,
    solaire[["timestamp", "ALLSKY_SFC_SW_DWN"]],
    on="timestamp",
    how="inner"
)

print(df.shape)

df.head()

(15872, 4)

,timestamp,DE_KN_residential1_grid_import,conso_horaire,ALLSKY_SFC_SW_DWN
0,2015-05-21 16:00:00,0.482,0.375,285.35
1,2015-05-21 17:00:00,1.045,0.563,87.95
2,2015-05-21 18:00:00,1.572,0.527,0.00
3,2015-05-21 19:00:00,2.152,0.580,0.00
4,2015-05-21 20:00:00,2.662,0.510,0.00

In [ ]:
print(df.shape)

print(df["timestamp"].min())

print(df["timestamp"].max())

(15872, 4)
2015-05-21 16:00:00
2017-03-12 23:00:00

In [ ]:
print(df.shape)

(15872, 4)

In [ ]:
df.head()

,timestamp,DE_KN_residential1_grid_import,conso_horaire,ALLSKY_SFC_SW_DWN
0,2015-05-21 16:00:00,0.482,0.375,285.35
1,2015-05-21 17:00:00,1.045,0.563,87.95
2,2015-05-21 18:00:00,1.572,0.527,0.00
3,2015-05-21 19:00:00,2.152,0.580,0.00
4,2015-05-21 20:00:00,2.662,0.510,0.00

In [ ]:
df["hour"] = df["timestamp"].dt.hour

df["dayofweek"] = df["timestamp"].dt.dayofweek

df["month"] = df["timestamp"].dt.month

df["lag_1"] = df["conso_horaire"].shift(1)

df["lag_24"] = df["conso_horaire"].shift(24)

df["rolling_24"] = (
    df["conso_horaire"]
    .rolling(24)
    .mean()
)

df = df.dropna()

print(df.shape)

(15848, 10)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

In [ ]:
X = df[
    [
        "hour",
        "dayofweek",
        "month",
        "lag_1",
        "lag_24",
        "rolling_24",
        "ALLSKY_SFC_SW_DWN"
    ]
]

y = df["conso_horaire"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    shuffle=False
)

In [ ]:
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

In [ ]:
mae = mean_absolute_error(y_test, pred)
r2 = r2_score(y_test, pred)

print("MAE :", mae)
print("R² :", r2)

MAE : 0.1733530747709077
R² : 0.29457442501925113

In [ ]:
importance = pd.DataFrame({
    "Variable": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

            Variable  Importance
3              lag_1    0.354341
5         rolling_24    0.194054
4             lag_24    0.147033
6  ALLSKY_SFC_SW_DWN    0.119525
0               hour    0.078221
2              month    0.056365
1          dayofweek    0.050462

In [ ]:
import pandas as pd

meteo = pd.read_csv(
    "../data/raw/meteo/ndjamena_meteo.csv"
)

meteo.head()

,time,temperature_2m,relative_humidity_2m,surface_pressure,wind_speed_10m
0,2020-01-01T00:00,19.7,23,978.4,14.5
1,2020-01-01T01:00,18.7,26,978.2,13.8
2,2020-01-01T02:00,18.0,29,978.0,12.8
3,2020-01-01T03:00,17.5,30,978.4,12.0
4,2020-01-01T04:00,17.0,32,978.5,11.9

In [ ]:
print(meteo.columns)

Index(['time', 'temperature_2m', 'relative_humidity_2m', 'surface_pressure',
       'wind_speed_10m'],
      dtype='str')

In [ ]:
meteo["time"] = pd.to_datetime(
    meteo["time"]
)

In [ ]:
print(meteo["time"].min())
print(meteo["time"].max())

2020-01-01 00:00:00
2025-12-31 23:00:00

In [ ]:
meteo["time"] = (
    pd.to_datetime(meteo["time"])
    .dt.tz_localize("UTC")
)

In [ ]:
print(meteo["time"].dtype)

datetime64[us, UTC]

In [ ]:
print(df.columns)
print(df.shape)

NameError: name 'df' is not defined

In [17]:
%whos

Variable   Type         Data/Info
---------------------------------
conso      DataFrame    Shape: (38454, 71)
meteo      DataFrame    Shape: (52608, 5)
np         module       <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
pd         module       <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
solaire    DataFrame    Shape: (220632, 5)

In [18]:
import pandas as pd

df_conso = pd.read_csv(
    "../data/raw/consommation/household_data_60min_singleindex.csv"
)

solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=14
)

In [19]:
df_conso["timestamp"] = pd.to_datetime(df_conso["timestamp"], utc=True)

KeyError: 'timestamp'

In [20]:
df_conso["timestamp"] = pd.to_datetime(
    df_conso["utc_timestamp"],
    utc=True
)

In [21]:
print(df_conso.columns)
print(df_conso.head())

Index(['utc_timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices',
       'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2',
       'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4',
       'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate',
       'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher',
       'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import',
       'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2',
       'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4',
       'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade',
       'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator',
       'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import',
       'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher',
       'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import',
       'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv',
       'DE_KN_residential1_washing_machine',
       'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher',
       'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import',
       'DE_KN_residential2_washing_machine',
       'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher',
       'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export',
       'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv',
       'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine',
       'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev',
       'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export',
       'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump',
       'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator',
       'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher',
       'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator',
       'DE_KN_residential5_washing_machine',
       'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher',
       'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export',
       'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'timestamp'],
      dtype='str')
          utc_timestamp        cet_cest_timestamp  \
0  2014-12-11T17:00:00Z  2014-12-11T18:00:00+0100
1  2014-12-11T18:00:00Z  2014-12-11T19:00:00+0100
2  2014-12-11T19:00:00Z  2014-12-11T20:00:00+0100
3  2014-12-11T20:00:00Z  2014-12-11T21:00:00+0100
4  2014-12-11T21:00:00Z  2014-12-11T22:00:00+0100

   DE_KN_industrial1_grid_import  DE_KN_industrial1_pv_1  \
0                            NaN                     NaN
1                            NaN                     NaN
2                            NaN                     NaN
3                            NaN                     NaN
4                            NaN                     NaN

   DE_KN_industrial1_pv_2  DE_KN_industrial2_grid_import  \
0                     NaN                            NaN
1                     NaN                            NaN
2                     NaN                            NaN
3                     NaN                            NaN
4                     NaN                            NaN

   DE_KN_industrial2_pv  DE_KN_industrial2_storage_charge  \
0                   NaN                               NaN
1                   NaN                               NaN
2                   NaN                               NaN
3                   NaN                               NaN
4                   NaN                               NaN

   DE_KN_industrial2_storage_decharge  DE_KN_industrial3_area_offices  ...  \
0                                 NaN                             NaN  ...
1                                 NaN                             NaN  ...
2                                 NaN                             NaN  ...
3                                 NaN                             NaN  ...
4                                 NaN                             NaN  ...

   DE_KN_residential5_washing_machine  DE_KN_residential6_circulation_pump  \
0                                 NaN                                  NaN
1                                 NaN                                  NaN
2                                 NaN                                  NaN
3                                 NaN                                  NaN
4                                 NaN                                  NaN

   DE_KN_residential6_dishwasher  DE_KN_residential6_freezer  \
0                            NaN                         NaN
1                            NaN                         NaN
2                            NaN                         NaN
3                            NaN                         NaN
4                            NaN                         NaN

   DE_KN_residential6_grid_export  DE_KN_residential6_grid_import  \
0                             NaN                             NaN
1                             NaN                             NaN
2                             NaN                             NaN
3                             NaN                             NaN
4                             NaN                             NaN

   DE_KN_residential6_pv  DE_KN_residential6_washing_machine  interpolated  \
0                    NaN                                 NaN           NaN
1                    NaN                                 NaN           NaN
2                    NaN                                 NaN           NaN
3                    NaN                                 NaN           NaN
4                    NaN                                 NaN           NaN

                  timestamp
0 2014-12-11 17:00:00+00:00
1 2014-12-11 18:00:00+00:00
2 2014-12-11 19:00:00+00:00
3 2014-12-11 20:00:00+00:00
4 2014-12-11 21:00:00+00:00

[5 rows x 72 columns]

In [23]:
print(solaire.columns)
print(solaire["timestamp"].dtype)

print(df_conso["timestamp"].dtype)

Index(['2001', '4', '1', '4.1', '0.0'], dtype='str')

KeyError: 'timestamp'

In [24]:
print(solaire.columns)
print(solaire["timestamp"].dtype)

print(df_conso["timestamp"].dtype)

Index(['2001', '4', '1', '4.1', '0.0'], dtype='str')

KeyError: 'timestamp'

In [25]:
solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=15
)

print(solaire.columns)

Index(['2001', '4', '1', '5', '0.0'], dtype='str')

In [26]:
solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=16
)

print(solaire.columns)

Index(['2001', '4', '1', '6', '59.62'], dtype='str')

In [28]:
solaire = pd.read_csv(
    "../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv",
    skiprows=17
)

print(solaire.columns)

Index(['2001', '4', '1', '7', '256.15'], dtype='str')

In [29]:
with open("../data/raw/solaire/POWER_Point_Hourly_20010401_20260601_012d11N_015d05E_LST.csv") as f:
    for i in range(20):
        print(i, f.readline().strip())

0 -BEGIN HEADER-
1 NASA/POWER Source Native Resolution Hourly Data
2 Dates (month/day/year): 04/01/2001 through 06/01/2026 in LST
3 Location: Latitude  12.11   Longitude 15.05
4 Elevation from MERRA-2: Average for 0.5 x 0.625 degree lat/lon region = 295.58 meters
5 The value for missing source data that cannot be computed or is outside of the sources availability range: -999
6 Parameter(s):
7 ALLSKY_SFC_SW_DWN     CERES SYN1deg All Sky Surface Shortwave Downward Irradiance (Wh/m^2)
8 -END HEADER-
9 YEAR,MO,DY,HR,ALLSKY_SFC_SW_DWN
10 2001,4,1,0,0.0
11 2001,4,1,1,0.0
12 2001,4,1,2,0.0
13 2001,4,1,3,0.0
14 2001,4,1,4,0.0
15 2001,4,1,5,0.0
16 2001,4,1,6,59.62
17 2001,4,1,7,256.15
18 2001,4,1,8,507.4
19 2001,4,1,9,730.97

In [32]:
import pandas as pd

solaire = pd.read_csv(
    "...data/raw/solar/nasa_power.csv",
    skiprows=9
)

print(solaire.head())
print(solaire.columns)

FileNotFoundError: [Errno 2] No such file or directory: '...data/raw/solar/nasa_power.csv'

In [31]:
import pandas as pd

solaire = pd.read_csv(
    "data/raw/solar/nasa_power.csv"
)

print(solaire.shape)
print(solaire.columns)
print(solaire.head())

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/solar/nasa_power.csv'

In [33]:
print(df_conso.columns)

Index(['utc_timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices',
       'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2',
       'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4',
       'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate',
       'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher',
       'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import',
       'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2',
       'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4',
       'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade',
       'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator',
       'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import',
       'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher',
       'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import',
       'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv',
       'DE_KN_residential1_washing_machine',
       'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher',
       'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import',
       'DE_KN_residential2_washing_machine',
       'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher',
       'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export',
       'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv',
       'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine',
       'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev',
       'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export',
       'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump',
       'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator',
       'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher',
       'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator',
       'DE_KN_residential5_washing_machine',
       'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher',
       'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export',
       'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'timestamp'],
      dtype='str')

In [34]:
print(df_conso.shape)

(38454, 72)

In [36]:
import os

for root, dirs, files in os.walk("data"):
    for file in files:
        if "POWER" in file or "solar" in file.lower():
            print(os.path.join(root, file))

In [37]:
import os

for root, dirs, files in os.walk("data"):
    for file in files:
        print(os.path.join(root, file))

In [38]:
for root, dirs, files in os.walk("data"):
    for file in files:
        print(os.path.join(root, file))

In [39]:
print("solaire" in globals())
print("meteo" in globals())

True
True

In [40]:
print(solaire.shape)
print(solaire.columns)
print(solaire.head())

(220624, 5)
Index(['2001', '4', '1', '7', '256.15'], dtype='str')
   2001  4  1   7   256.15
0  2001  4  1   8   507.40
1  2001  4  1   9   730.97
2  2001  4  1  10   914.20
3  2001  4  1  11   931.92
4  2001  4  1  12  1043.22

In [41]:
print("timestamp" in solaire.columns)

False

In [42]:
print(df_conso["timestamp"].min())
print(df_conso["timestamp"].max())

print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

2014-12-11 17:00:00+00:00
2019-05-01 22:00:00+00:00

KeyError: 'timestamp'

In [43]:
solaire.columns = [
    "YEAR",
    "MO",
    "DY",
    "HR",
    "ALLSKY_SFC_SW_DWN"
]

In [44]:
print(solaire.head())
print(solaire.columns)

   YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN
0  2001   4   1   8             507.40
1  2001   4   1   9             730.97
2  2001   4   1  10             914.20
3  2001   4   1  11             931.92
4  2001   4   1  12            1043.22
Index(['YEAR', 'MO', 'DY', 'HR', 'ALLSKY_SFC_SW_DWN'], dtype='str')

In [45]:
solaire["timestamp"] = pd.to_datetime(
    solaire[["YEAR","MO","DY","HR"]]
    .rename(columns={
        "YEAR":"year",
        "MO":"month",
        "DY":"day",
        "HR":"hour"
    })
)

In [46]:
solaire["timestamp"] = (
    solaire["timestamp"]
    .dt.tz_localize("UTC")
)

In [47]:
print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

print(df_conso["timestamp"].min())
print(df_conso["timestamp"].max())

2001-04-01 08:00:00+00:00
2026-06-01 23:00:00+00:00
2014-12-11 17:00:00+00:00
2019-05-01 22:00:00+00:00

In [48]:
df = pd.merge(
    df_conso,
    solaire[["timestamp", "ALLSKY_SFC_SW_DWN"]],
    on="timestamp",
    how="inner"
)

print(df.shape)

(38454, 73)

In [49]:
print(df.shape)

(38454, 73)

In [50]:
print(meteo.columns)
print(meteo.head())

Index(['time', 'temperature_2m', 'relative_humidity_2m', 'surface_pressure',
       'wind_speed_10m'],
      dtype='str')
                 time  temperature_2m  relative_humidity_2m  surface_pressure  \
0 2020-01-01 00:00:00            19.7                    23             978.4
1 2020-01-01 01:00:00            18.7                    26             978.2
2 2020-01-01 02:00:00            18.0                    29             978.0
3 2020-01-01 03:00:00            17.5                    30             978.4
4 2020-01-01 04:00:00            17.0                    32             978.5

   wind_speed_10m
0            14.5
1            13.8
2            12.8
3            12.0
4            11.9

In [52]:
meteo["time"] = pd.to_datetime(meteo["time"])

meteo["time"] = (
    meteo["time"]
    .dt.tz_localize("UTC")
)

TypeError: Already tz-aware, use tz_convert to convert.

In [53]:
meteo["time"] = pd.to_datetime(meteo["time"])

In [55]:
print(meteo["time"].dtype)
print(df_conso["timestamp"].dtype)
print(solaire["timestamp"].dtype)

datetime64[us, UTC]
datetime64[us, UTC]
datetime64[us, UTC]

In [56]:
df = pd.merge(
    df_conso,
    meteo,
    left_on="timestamp",
    right_on="time",
    how="inner"
)

print(df.shape)
print(df.head())

(0, 77)
Empty DataFrame
Columns: [utc_timestamp, cet_cest_timestamp, DE_KN_industrial1_grid_import, DE_KN_industrial1_pv_1, DE_KN_industrial1_pv_2, DE_KN_industrial2_grid_import, DE_KN_industrial2_pv, DE_KN_industrial2_storage_charge, DE_KN_industrial2_storage_decharge, DE_KN_industrial3_area_offices, DE_KN_industrial3_area_room_1, DE_KN_industrial3_area_room_2, DE_KN_industrial3_area_room_3, DE_KN_industrial3_area_room_4, DE_KN_industrial3_compressor, DE_KN_industrial3_cooling_aggregate, DE_KN_industrial3_cooling_pumps, DE_KN_industrial3_dishwasher, DE_KN_industrial3_ev, DE_KN_industrial3_grid_import, DE_KN_industrial3_machine_1, DE_KN_industrial3_machine_2, DE_KN_industrial3_machine_3, DE_KN_industrial3_machine_4, DE_KN_industrial3_machine_5, DE_KN_industrial3_pv_facade, DE_KN_industrial3_pv_roof, DE_KN_industrial3_refrigerator, DE_KN_industrial3_ventilation, DE_KN_public1_grid_import, DE_KN_public2_grid_import, DE_KN_residential1_dishwasher, DE_KN_residential1_freezer, DE_KN_residential1_grid_import, DE_KN_residential1_heat_pump, DE_KN_residential1_pv, DE_KN_residential1_washing_machine, DE_KN_residential2_circulation_pump, DE_KN_residential2_dishwasher, DE_KN_residential2_freezer, DE_KN_residential2_grid_import, DE_KN_residential2_washing_machine, DE_KN_residential3_circulation_pump, DE_KN_residential3_dishwasher, DE_KN_residential3_freezer, DE_KN_residential3_grid_export, DE_KN_residential3_grid_import, DE_KN_residential3_pv, DE_KN_residential3_refrigerator, DE_KN_residential3_washing_machine, DE_KN_residential4_dishwasher, DE_KN_residential4_ev, DE_KN_residential4_freezer, DE_KN_residential4_grid_export, DE_KN_residential4_grid_import, DE_KN_residential4_heat_pump, DE_KN_residential4_pv, DE_KN_residential4_refrigerator, DE_KN_residential4_washing_machine, DE_KN_residential5_dishwasher, DE_KN_residential5_grid_import, DE_KN_residential5_refrigerator, DE_KN_residential5_washing_machine, DE_KN_residential6_circulation_pump, DE_KN_residential6_dishwasher, DE_KN_residential6_freezer, DE_KN_residential6_grid_export, DE_KN_residential6_grid_import, DE_KN_residential6_pv, DE_KN_residential6_washing_machine, interpolated, timestamp, time, temperature_2m, relative_humidity_2m, surface_pressure, wind_speed_10m]
Index: []

[0 rows x 77 columns]

In [57]:
print(df.columns)

Index(['utc_timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import',
       'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2',
       'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv',
       'DE_KN_industrial2_storage_charge',
       'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices',
       'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2',
       'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4',
       'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate',
       'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher',
       'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import',
       'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2',
       'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4',
       'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade',
       'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator',
       'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import',
       'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher',
       'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import',
       'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv',
       'DE_KN_residential1_washing_machine',
       'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher',
       'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import',
       'DE_KN_residential2_washing_machine',
       'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher',
       'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export',
       'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv',
       'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine',
       'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev',
       'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export',
       'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump',
       'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator',
       'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher',
       'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator',
       'DE_KN_residential5_washing_machine',
       'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher',
       'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export',
       'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv',
       'DE_KN_residential6_washing_machine', 'interpolated', 'timestamp',
       'time', 'temperature_2m', 'relative_humidity_2m', 'surface_pressure',
       'wind_speed_10m'],
      dtype='str')

In [58]:
df = pd.merge(
    df,
    solaire[["timestamp", "ALLSKY_SFC_SW_DWN"]],
    on="timestamp",
    how="inner"
)

print(df.shape)

(0, 78)

In [59]:
print(df[[
    "conso_horaire",
    "temperature_2m",
    "relative_humidity_2m",
    "surface_pressure",
    "wind_speed_10m",
    "ALLSKY_SFC_SW_DWN"
]].head())

KeyError: "['conso_horaire'] not in index"

In [60]:
print(df.shape)

print(df.columns.tolist())

(0, 78)
['utc_timestamp', 'cet_cest_timestamp', 'DE_KN_industrial1_grid_import', 'DE_KN_industrial1_pv_1', 'DE_KN_industrial1_pv_2', 'DE_KN_industrial2_grid_import', 'DE_KN_industrial2_pv', 'DE_KN_industrial2_storage_charge', 'DE_KN_industrial2_storage_decharge', 'DE_KN_industrial3_area_offices', 'DE_KN_industrial3_area_room_1', 'DE_KN_industrial3_area_room_2', 'DE_KN_industrial3_area_room_3', 'DE_KN_industrial3_area_room_4', 'DE_KN_industrial3_compressor', 'DE_KN_industrial3_cooling_aggregate', 'DE_KN_industrial3_cooling_pumps', 'DE_KN_industrial3_dishwasher', 'DE_KN_industrial3_ev', 'DE_KN_industrial3_grid_import', 'DE_KN_industrial3_machine_1', 'DE_KN_industrial3_machine_2', 'DE_KN_industrial3_machine_3', 'DE_KN_industrial3_machine_4', 'DE_KN_industrial3_machine_5', 'DE_KN_industrial3_pv_facade', 'DE_KN_industrial3_pv_roof', 'DE_KN_industrial3_refrigerator', 'DE_KN_industrial3_ventilation', 'DE_KN_public1_grid_import', 'DE_KN_public2_grid_import', 'DE_KN_residential1_dishwasher', 'DE_KN_residential1_freezer', 'DE_KN_residential1_grid_import', 'DE_KN_residential1_heat_pump', 'DE_KN_residential1_pv', 'DE_KN_residential1_washing_machine', 'DE_KN_residential2_circulation_pump', 'DE_KN_residential2_dishwasher', 'DE_KN_residential2_freezer', 'DE_KN_residential2_grid_import', 'DE_KN_residential2_washing_machine', 'DE_KN_residential3_circulation_pump', 'DE_KN_residential3_dishwasher', 'DE_KN_residential3_freezer', 'DE_KN_residential3_grid_export', 'DE_KN_residential3_grid_import', 'DE_KN_residential3_pv', 'DE_KN_residential3_refrigerator', 'DE_KN_residential3_washing_machine', 'DE_KN_residential4_dishwasher', 'DE_KN_residential4_ev', 'DE_KN_residential4_freezer', 'DE_KN_residential4_grid_export', 'DE_KN_residential4_grid_import', 'DE_KN_residential4_heat_pump', 'DE_KN_residential4_pv', 'DE_KN_residential4_refrigerator', 'DE_KN_residential4_washing_machine', 'DE_KN_residential5_dishwasher', 'DE_KN_residential5_grid_import', 'DE_KN_residential5_refrigerator', 'DE_KN_residential5_washing_machine', 'DE_KN_residential6_circulation_pump', 'DE_KN_residential6_dishwasher', 'DE_KN_residential6_freezer', 'DE_KN_residential6_grid_export', 'DE_KN_residential6_grid_import', 'DE_KN_residential6_pv', 'DE_KN_residential6_washing_machine', 'interpolated', 'timestamp', 'time', 'temperature_2m', 'relative_humidity_2m', 'surface_pressure', 'wind_speed_10m', 'ALLSKY_SFC_SW_DWN']

In [61]:
print(df.head())

Empty DataFrame
Columns: [utc_timestamp, cet_cest_timestamp, DE_KN_industrial1_grid_import, DE_KN_industrial1_pv_1, DE_KN_industrial1_pv_2, DE_KN_industrial2_grid_import, DE_KN_industrial2_pv, DE_KN_industrial2_storage_charge, DE_KN_industrial2_storage_decharge, DE_KN_industrial3_area_offices, DE_KN_industrial3_area_room_1, DE_KN_industrial3_area_room_2, DE_KN_industrial3_area_room_3, DE_KN_industrial3_area_room_4, DE_KN_industrial3_compressor, DE_KN_industrial3_cooling_aggregate, DE_KN_industrial3_cooling_pumps, DE_KN_industrial3_dishwasher, DE_KN_industrial3_ev, DE_KN_industrial3_grid_import, DE_KN_industrial3_machine_1, DE_KN_industrial3_machine_2, DE_KN_industrial3_machine_3, DE_KN_industrial3_machine_4, DE_KN_industrial3_machine_5, DE_KN_industrial3_pv_facade, DE_KN_industrial3_pv_roof, DE_KN_industrial3_refrigerator, DE_KN_industrial3_ventilation, DE_KN_public1_grid_import, DE_KN_public2_grid_import, DE_KN_residential1_dishwasher, DE_KN_residential1_freezer, DE_KN_residential1_grid_import, DE_KN_residential1_heat_pump, DE_KN_residential1_pv, DE_KN_residential1_washing_machine, DE_KN_residential2_circulation_pump, DE_KN_residential2_dishwasher, DE_KN_residential2_freezer, DE_KN_residential2_grid_import, DE_KN_residential2_washing_machine, DE_KN_residential3_circulation_pump, DE_KN_residential3_dishwasher, DE_KN_residential3_freezer, DE_KN_residential3_grid_export, DE_KN_residential3_grid_import, DE_KN_residential3_pv, DE_KN_residential3_refrigerator, DE_KN_residential3_washing_machine, DE_KN_residential4_dishwasher, DE_KN_residential4_ev, DE_KN_residential4_freezer, DE_KN_residential4_grid_export, DE_KN_residential4_grid_import, DE_KN_residential4_heat_pump, DE_KN_residential4_pv, DE_KN_residential4_refrigerator, DE_KN_residential4_washing_machine, DE_KN_residential5_dishwasher, DE_KN_residential5_grid_import, DE_KN_residential5_refrigerator, DE_KN_residential5_washing_machine, DE_KN_residential6_circulation_pump, DE_KN_residential6_dishwasher, DE_KN_residential6_freezer, DE_KN_residential6_grid_export, DE_KN_residential6_grid_import, DE_KN_residential6_pv, DE_KN_residential6_washing_machine, interpolated, timestamp, time, temperature_2m, relative_humidity_2m, surface_pressure, wind_speed_10m, ALLSKY_SFC_SW_DWN]
Index: []

[0 rows x 78 columns]

In [62]:
print("CONSO")
print(df_conso["timestamp"].min())
print(df_conso["timestamp"].max())

print("\nMETEO")
print(meteo["time"].min())
print(meteo["time"].max())

print("\nSOLAIRE")
print(solaire["timestamp"].min())
print(solaire["timestamp"].max())

CONSO
2014-12-11 17:00:00+00:00
2019-05-01 22:00:00+00:00

METEO
2020-01-01 00:00:00+00:00
2025-12-31 23:00:00+00:00

SOLAIRE
2001-04-01 08:00:00+00:00
2026-06-01 23:00:00+00:00

In [63]:
print(df_conso["timestamp"].head())
print(meteo["time"].head())
print(solaire["timestamp"].head())

0   2014-12-11 17:00:00+00:00
1   2014-12-11 18:00:00+00:00
2   2014-12-11 19:00:00+00:00
3   2014-12-11 20:00:00+00:00
4   2014-12-11 21:00:00+00:00
Name: timestamp, dtype: datetime64[us, UTC]
0   2020-01-01 00:00:00+00:00
1   2020-01-01 01:00:00+00:00
2   2020-01-01 02:00:00+00:00
3   2020-01-01 03:00:00+00:00
4   2020-01-01 04:00:00+00:00
Name: time, dtype: datetime64[us, UTC]
0   2001-04-01 08:00:00+00:00
1   2001-04-01 09:00:00+00:00
2   2001-04-01 10:00:00+00:00
3   2001-04-01 11:00:00+00:00
4   2001-04-01 12:00:00+00:00
Name: timestamp, dtype: datetime64[us, UTC]

In [66]:
print(meteo["time"].min())
print(meteo["time"].max())
print(meteo.shape)

2020-01-01 00:00:00+00:00
2025-12-31 23:00:00+00:00
(52608, 5)

In [68]:
df_conso["conso_horaire"] = df_conso["DE_KN_residential1_grid_import"]

In [69]:
df = df_conso.copy()

df["hour"] = df["timestamp"].dt.hour
df["dayofweek"] = df["timestamp"].dt.dayofweek
df["month"] = df["timestamp"].dt.month

In [70]:
df["lag_1"] = df["conso_horaire"].shift(1)

df["lag_24"] = df["conso_horaire"].shift(24)

df["rolling_24"] = (
    df["conso_horaire"]
    .shift(1)
    .rolling(window=24)
    .mean()
)

In [71]:
df = df.dropna()

print(df.shape)

(0, 79)

In [72]:
features = [
    "hour",
    "dayofweek",
    "month",
    "lag_1",
    "lag_24",
    "rolling_24"
]

X = df[features]

y = df["conso_horaire"]

print(X.shape)
print(y.shape)

(0, 6)
(0,)

In [73]:

split = int(len(df) * 0.8)

X_train = X.iloc[:split]
X_test  = X.iloc[split:]

y_train = y.iloc[:split]
y_test  = y.iloc[split:]

In [74]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

ValueError: Found array with 0 sample(s) (shape=(0, 6)) while a minimum of 1 is required by RandomForestRegressor.

In [75]:
print(df_conso.shape)

print(
    df_conso["DE_KN_residential1_grid_import"]
    .isna()
    .sum()
)

print(
    df_conso["DE_KN_residential1_grid_import"]
    .notna()
    .sum()
)

(38454, 73)
22581
15873

In [76]:
df_conso["conso_horaire"] = df_conso["DE_KN_residential1_grid_import"]

print(df_conso["conso_horaire"].isna().sum())
print(df_conso["conso_horaire"].notna().sum())

22581
15873

In [77]:
df = df_conso.copy()

df["hour"] = df["timestamp"].dt.hour
df["dayofweek"] = df["timestamp"].dt.dayofweek
df["month"] = df["timestamp"].dt.month

df["lag_1"] = df["conso_horaire"].shift(1)
df["lag_24"] = df["conso_horaire"].shift(24)

df["rolling_24"] = (
    df["conso_horaire"]
    .shift(1)
    .rolling(24)
    .mean()
)

print(df.shape)

print(df[[
    "conso_horaire",
    "lag_1",
    "lag_24",
    "rolling_24"
]].head(30))

(38454, 79)
    conso_horaire  lag_1  lag_24  rolling_24
0             NaN    NaN     NaN         NaN
1             NaN    NaN     NaN         NaN
2             NaN    NaN     NaN         NaN
3             NaN    NaN     NaN         NaN
4             NaN    NaN     NaN         NaN
5             NaN    NaN     NaN         NaN
6             NaN    NaN     NaN         NaN
7             NaN    NaN     NaN         NaN
8             NaN    NaN     NaN         NaN
9             NaN    NaN     NaN         NaN
10            NaN    NaN     NaN         NaN
11            NaN    NaN     NaN         NaN
12            NaN    NaN     NaN         NaN
13            NaN    NaN     NaN         NaN
14            NaN    NaN     NaN         NaN
15            NaN    NaN     NaN         NaN
16            NaN    NaN     NaN         NaN
17            NaN    NaN     NaN         NaN
18            NaN    NaN     NaN         NaN
19            NaN    NaN     NaN         NaN
20            NaN    NaN     NaN         NaN
21            NaN    NaN     NaN         NaN
22            NaN    NaN     NaN         NaN
23            NaN    NaN     NaN         NaN
24            NaN    NaN     NaN         NaN
25            NaN    NaN     NaN         NaN
26            NaN    NaN     NaN         NaN
27            NaN    NaN     NaN         NaN
28            NaN    NaN     NaN         NaN
29            NaN    NaN     NaN         NaN

In [79]:
col = "DE_KN_residential1_grid_import"

print(df_conso[col].first_valid_index())
print(df_conso[col].last_valid_index())

3862
19734

In [80]:
col = "DE_KN_residential1_grid_import"

print(df_conso[col].first_valid_index())
print(df_conso[col].last_valid_index())

3862
19734

In [81]:
col = "DE_KN_residential1_grid_import"

debut = df_conso[col].first_valid_index()

print(
    df_conso.loc[
        debut:debut+10,
        ["timestamp", col]
    ]
)

                     timestamp  DE_KN_residential1_grid_import
3862 2015-05-21 15:00:00+00:00                           0.107
3863 2015-05-21 16:00:00+00:00                           0.482
3864 2015-05-21 17:00:00+00:00                           1.045
3865 2015-05-21 18:00:00+00:00                           1.572
3866 2015-05-21 19:00:00+00:00                           2.152
3867 2015-05-21 20:00:00+00:00                           2.662
3868 2015-05-21 21:00:00+00:00                           3.104
3869 2015-05-21 22:00:00+00:00                           3.417
3870 2015-05-21 23:00:00+00:00                           3.737
3871 2015-05-22 00:00:00+00:00                           4.037
3872 2015-05-22 01:00:00+00:00                           4.347

In [82]:
valides.sort_values(ascending=False).head(20)

NameError: name 'valides' is not defined

In [83]:
print(
    df_conso.notna()
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

utc_timestamp                          38454
cet_cest_timestamp                     38454
timestamp                              38454
DE_KN_residential3_circulation_pump    33210
interpolated                           31797
DE_KN_residential5_grid_import         30804
DE_KN_residential3_washing_machine     30546
DE_KN_residential3_dishwasher          29097
DE_KN_residential3_freezer             28732
DE_KN_residential3_refrigerator        25101
DE_KN_residential2_washing_machine     24733
DE_KN_residential5_washing_machine     23541
DE_KN_residential5_dishwasher          23541
DE_KN_residential3_grid_export         22555
DE_KN_residential3_pv                  22555
DE_KN_residential6_circulation_pump    21534
DE_KN_residential6_grid_import         21534
DE_KN_residential6_pv                  21534
DE_KN_residential4_grid_export         20360
DE_KN_residential4_pv                  20360
dtype: int64

In [84]:
print(df_conso["DE_KN_residential1_grid_import"].describe())

count    15873.000000
mean      4447.247439
std       2650.618053
min          0.107000
25%       2044.053000
50%       4509.818000
75%       6689.398000
max       9096.383000
Name: DE_KN_residential1_grid_import, dtype: float64

In [85]:
df_conso.notna().sum().sort_values(ascending=False).head(20)

utc_timestamp                          38454
cet_cest_timestamp                     38454
timestamp                              38454
DE_KN_residential3_circulation_pump    33210
interpolated                           31797
DE_KN_residential5_grid_import         30804
DE_KN_residential3_washing_machine     30546
DE_KN_residential3_dishwasher          29097
DE_KN_residential3_freezer             28732
DE_KN_residential3_refrigerator        25101
DE_KN_residential2_washing_machine     24733
DE_KN_residential5_washing_machine     23541
DE_KN_residential5_dishwasher          23541
DE_KN_residential3_grid_export         22555
DE_KN_residential3_pv                  22555
DE_KN_residential6_circulation_pump    21534
DE_KN_residential6_grid_import         21534
DE_KN_residential6_pv                  21534
DE_KN_residential4_grid_export         20360
DE_KN_residential4_pv                  20360
dtype: int64

In [86]:
df = df_conso.copy()

df["conso_horaire"] = df["DE_KN_residential5_grid_import"]

In [87]:
print(df["conso_horaire"].notna().sum())

30804

In [88]:
df["hour"] = df["timestamp"].dt.hour
df["dayofweek"] = df["timestamp"].dt.dayofweek
df["month"] = df["timestamp"].dt.month

df["lag_1"] = df["conso_horaire"].shift(1)
df["lag_24"] = df["conso_horaire"].shift(24)

df["rolling_24"] = (
    df["conso_horaire"]
    .shift(1)
    .rolling(24)
    .mean()
)

In [90]:
df = df.dropna()

print(df.shape)

(0, 79)

In [91]:
features = [
    "hour",
    "dayofweek",
    "month",
    "lag_1",
    "lag_24",
    "rolling_24"
]

X = df[features]
y = df["conso_horaire"]

print(X.shape)
print(y.shape)

(0, 6)
(0,)

In [92]:
print(df["conso_horaire"].isna().sum())

print(df["lag_1"].isna().sum())

print(df["lag_24"].isna().sum())

print(df["rolling_24"].isna().sum())

0
0
0
0

In [93]:
print(df[[
    "conso_horaire",
    "lag_1",
    "lag_24",
    "rolling_24"
]].tail(20))

Empty DataFrame
Columns: [conso_horaire, lag_1, lag_24, rolling_24]
Index: []

In [94]:
print(
    df[[
        "conso_horaire",
        "lag_1",
        "lag_24",
        "rolling_24"
    ]]
    .notna()
    .all(axis=1)
    .sum()
)

0

In [95]:
print(df_conso["DE_KN_residential5_grid_import"].notna().sum())
print(df_conso["DE_KN_residential5_grid_import"].isna().sum())

30804
7650

In [96]:
print(
    df_conso[
        ["timestamp", "DE_KN_residential5_grid_import"]
    ].dropna().head(20)
)

                     timestamp  DE_KN_residential5_grid_import
7650 2015-10-26 11:00:00+00:00                           0.045
7651 2015-10-26 12:00:00+00:00                           0.395
7652 2015-10-26 13:00:00+00:00                           0.865
7653 2015-10-26 14:00:00+00:00                           1.085
7654 2015-10-26 15:00:00+00:00                           1.325
7655 2015-10-26 16:00:00+00:00                           1.435
7656 2015-10-26 17:00:00+00:00                           1.645
7657 2015-10-26 18:00:00+00:00                           1.885
7658 2015-10-26 19:00:00+00:00                           2.550
7659 2015-10-26 20:00:00+00:00                           2.860
7660 2015-10-26 21:00:00+00:00                           3.615
7661 2015-10-26 22:00:00+00:00                           3.875
7662 2015-10-26 23:00:00+00:00                           4.090
7663 2015-10-27 00:00:00+00:00                           4.300
7664 2015-10-27 01:00:00+00:00                           4.485
7665 2015-10-27 02:00:00+00:00                           4.705
7666 2015-10-27 03:00:00+00:00                           4.875
7667 2015-10-27 04:00:00+00:00                           5.105
7668 2015-10-27 05:00:00+00:00                           5.400
7669 2015-10-27 06:00:00+00:00                           6.280

In [97]:
print(
    df_conso[
        ["timestamp", "DE_KN_residential5_grid_import"]
    ].dropna().tail(20)
)

                      timestamp  DE_KN_residential5_grid_import
38434 2019-05-01 03:00:00+00:00                        8766.395
38435 2019-05-01 04:00:00+00:00                        8766.630
38436 2019-05-01 05:00:00+00:00                        8766.890
38437 2019-05-01 06:00:00+00:00                        8767.125
38438 2019-05-01 07:00:00+00:00                        8768.080
38439 2019-05-01 08:00:00+00:00                        8768.875
38440 2019-05-01 09:00:00+00:00                        8769.170
38441 2019-05-01 10:00:00+00:00                        8769.890
38442 2019-05-01 11:00:00+00:00                        8770.119
38443 2019-05-01 12:00:00+00:00                        8770.425
38444 2019-05-01 13:00:00+00:00                        8770.745
38445 2019-05-01 14:00:00+00:00                        8771.000
38446 2019-05-01 15:00:00+00:00                        8771.220
38447 2019-05-01 16:00:00+00:00                        8771.484
38448 2019-05-01 17:00:00+00:00                        8771.889
38449 2019-05-01 18:00:00+00:00                        8772.698
38450 2019-05-01 19:00:00+00:00                        8773.055
38451 2019-05-01 20:00:00+00:00                        8773.380
38452 2019-05-01 21:00:00+00:00                        8773.750
38453 2019-05-01 22:00:00+00:00                        8773.800

In [98]:
df = df_conso.copy()

df["conso_horaire"] = (
    df["DE_KN_residential5_grid_import"]
    .interpolate()
)

print(df["conso_horaire"].isna().sum())

7650

In [99]:
print(df_conso["DE_KN_residential5_grid_import"].notna().sum())
print(df_conso["DE_KN_residential5_grid_import"].isna().sum())

30804
7650

In [101]:
import pandas as pd

df_conso = pd.read_csv(
    "...data/raw/consumption/opsd-household_data.csv"
)

FileNotFoundError: [Errno 2] No such file or directory: '...data/raw/consumption/opsd-household_data.csv'

In [102]:
valides = df_conso.notna().sum()

print(valides.sort_values(ascending=False).head(30))

utc_timestamp                          38454
cet_cest_timestamp                     38454
timestamp                              38454
DE_KN_residential3_circulation_pump    33210
interpolated                           31797
DE_KN_residential5_grid_import         30804
DE_KN_residential3_washing_machine     30546
DE_KN_residential3_dishwasher          29097
DE_KN_residential3_freezer             28732
DE_KN_residential3_refrigerator        25101
DE_KN_residential2_washing_machine     24733
DE_KN_residential5_washing_machine     23541
DE_KN_residential5_dishwasher          23541
DE_KN_residential3_grid_export         22555
DE_KN_residential3_pv                  22555
DE_KN_residential6_circulation_pump    21534
DE_KN_residential6_grid_import         21534
DE_KN_residential6_pv                  21534
DE_KN_residential4_grid_export         20360
DE_KN_residential4_pv                  20360
DE_KN_residential4_grid_import         20360
DE_KN_residential4_freezer             20288
DE_KN_residential4_ev                  20288
DE_KN_residential2_circulation_pump    19823
DE_KN_residential2_dishwasher          19134
DE_KN_industrial1_pv_1                 17288
DE_KN_industrial1_pv_2                 17288
DE_KN_residential6_grid_export         16690
DE_KN_industrial1_grid_import          16434
DE_KN_residential1_pv                  15873
dtype: int64

In [103]:
print(df_conso["DE_KN_residential5_grid_import"].head())
print(df_conso["DE_KN_residential5_grid_import"].describe())

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: DE_KN_residential5_grid_import, dtype: float64
count    30804.000000
mean      4690.131473
std       2612.506795
min          0.045000
25%       2254.501500
50%       4758.751000
75%       7195.823500
max       8773.800000
Name: DE_KN_residential5_grid_import, dtype: float64

In [104]:
df_conso[
    ["timestamp", "DE_KN_residential5_grid_import"]
].dropna().head()

                     timestamp  DE_KN_residential5_grid_import
7650 2015-10-26 11:00:00+00:00                           0.045
7651 2015-10-26 12:00:00+00:00                           0.395
7652 2015-10-26 13:00:00+00:00                           0.865
7653 2015-10-26 14:00:00+00:00                           1.085
7654 2015-10-26 15:00:00+00:00                           1.325

In [105]:
df_conso[
    ["timestamp", "DE_KN_residential5_grid_import"]
].dropna().tail()

                      timestamp  DE_KN_residential5_grid_import
38449 2019-05-01 18:00:00+00:00                        8772.698
38450 2019-05-01 19:00:00+00:00                        8773.055
38451 2019-05-01 20:00:00+00:00                        8773.380
38452 2019-05-01 21:00:00+00:00                        8773.750
38453 2019-05-01 22:00:00+00:00                        8773.800

In [106]:
print(df_conso["conso_horaire"].notna().sum())

15873

In [108]:
df_conso["hour"] = df_conso["timestamp"].dt.hour
df_conso["dayofweek"] = df_conso["timestamp"].dt.dayofweek
df_conso["month"] = df_conso["timestamp"].dt.month

In [109]:
df_conso["lag_1"] = df_conso["conso_horaire"].shift(1)

df_conso["lag_24"] = df_conso["conso_horaire"].shift(24)

df_conso["rolling_24"] = (
    df_conso["conso_horaire"]
    .rolling(24)
    .mean()
)

In [110]:
df_model = df_conso[
    [
        "conso_horaire",
        "hour",
        "dayofweek",
        "month",
        "lag_1",
        "lag_24",
        "rolling_24"
    ]
].dropna()

print(df_model.shape)

(15849, 7)

In [111]:
X = df_model[
    [
        "hour",
        "dayofweek",
        "month",
        "lag_1",
        "lag_24",
        "rolling_24"
    ]
]

y = df_model["conso_horaire"]

print(X.shape)
print(y.shape)

(15849, 6)
(15849,)

In [112]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(12679, 6)
(3170, 6)

In [113]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [114]:
from sklearn.metrics import mean_absolute_error, r2_score

pred = model.predict(X_test)

print("MAE :", mean_absolute_error(y_test, pred))
print("R² :", r2_score(y_test, pred))

MAE : 0.26110659621442767
R² : 0.999999975475413

In [115]:
print(df_model.shape)
print(X.shape)
print(y.shape)

(15849, 7)
(15849, 6)
(15849,)

In [116]:
importance = pd.DataFrame({
    "Variable": X.columns,
    "Importance": model.feature_importances_
})

print(
    importance.sort_values(
        by="Importance",
        ascending=False
    )
)

     Variable    Importance
5  rolling_24  3.509740e-01
4      lag_24  3.353294e-01
3       lag_1  3.136793e-01
2       month  1.653024e-05
1   dayofweek  6.571552e-07
0        hour  1.101195e-07